### ISSUE TITLE
[Feature] smooth quant or other quant method

### ISSUE THREAD

**Issue by MichoChan** [sgl-project/sglang#1355]
### Checklist

- [ ] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 2. Please use English, otherwise it will be closed.

### Motivation

there are some better quant method，but sglang/vllm only support awq、gptq

**Comment by zhyncs** [comment]
What do you mean by a better quant method? It's definitely not smoothquant. The support for smoothquant in the beginning of vLLM pr was developed by my previous team, and it's simply not suitable for production usage online due to its poor accuracy and performance, which is not much better than AWQ.

**Comment by MichoChan** [comment]
> What do you mean by a better quant method? It's definitely not smoothquant. The support for smoothquant in the beginning of vLLM pr was developed by my previous team, and it's simply not suitable for production usage online due to its poor accuracy and performance, which is not much better than AWQ.

thanks！how about this https://github.com/efeslab/Atom  ？
we found awq/gpt accuracy is not good enough in some scene

**Comment by zhyncs** [comment]
Currently, FP8(W8A8) in SGLang is a quantization method that can be used in production environments, developed by the CUTLASS team. Others like AWQ, GPTQ are only supported due to **community popularity**, the truly widely used one will be another W4A16 method, not AWQ nor GPTQ, it is a **proprietary** algorithm and implementation.

**Comment by zhyncs** [comment]
As far as I know, Atom is currently not adopted in various open-source or proprietary inference frameworks by major companies. However, it is an excellent research project. My previous team referenced and conducted research on Atom when proposing W4A8(QQQ), but of course, QQQ's accuracy is not suitable for production use. I think many methods nowadays are more for research purposes rather than practical use.

**Comment by MichoChan** [comment]
thanks very much！

**Comment by huanhuanlaoda** [comment]
> Currently, FP8(W8A8) in SGLang is a quantization method that can be used in production environments, developed by the CUTLASS team. Others like AWQ, GPTQ are only supported due to **community popularity**, the truly widely used one will be another W4A16 method, not AWQ nor GPTQ, it is a **proprietary** algorithm and implementation.

Could you please share more about this "proprietary" algorithm?

**Comment by zhyncs** [comment]
In terms of quantification, we will remove the dependency on vLLM in the next month and implement AWQ, GPTQ, FP8(W8A8), W4A16, W8A16 support in SGLang through torchao and other quantification libraries. This should meet the needs of most of the open-source community. The closed-source implementation mentioned in the issue reply cannot provide more information, thank you for understanding.
