### ISSUE TITLE
SRT performance single-core CPU bound

### ISSUE THREAD

**Issue by qeternity** [sgl-project/sglang#231]
Hi all,

After extensive testing, we find that the SRT backend is pretty CPU bound, often unable to saturate a single GPU at reasonable batch sizes unless using a latest gen consumer CPU with high single core performance.

For instance, a 4090 running on a 7402P performs significantly worse than a 3090ti running on a 7600X (equivalent Python/CUDA/Torch/etc versions)

I presume this is due to single threaded nature of the event loop that is serving uvicorn, but it is nonetheless a significant performance impediment. Additional constraints like regex massively impact serving performance as it appears that the FSMs are also running in this hot path.

Does anyone have any tips on mitigating this in production?

Thanks

**Comment by hnyls2002** [comment]
@qeternity Thanks for reporting this problem! We have also noticed the CPU is bound with Python's single thread limit. We will work further to optimize our performance.

As for the constrained decoding part, massive computation is only required when initializing the FSM/Jump-Forward mapping, and the running overhead is less than 3%. We would appreciate it if you could provide more details if you find highly significant overhead during running.

**Comment by qeternity** [comment]
The overhead is low _provided that you're not already CPU constrained_ (e.g. bs=1). But even on fast single core, I can easily drop perf by > 80% (albeit with a pretty crappy regex).

A simple test is to have a prompt that will cause a relatively long answer. Set max_tokens to something you will guarantee to hit (like 100).

Then run `gen("answer")` and `"Answer:" + gen("answer", regex=r" .*")`

This is sort of a hacky way to overcome the lack of token healing (although a very expensive way to do so). However in my testing, at some reasonable batch size (bs=32) you will see 4-5x worse performance with the regex contraint.

**Comment by Qubitium** [comment]
I see this problem all over python due to GIL not really srt or uvicorn specific. Any python code that does non-io work will render any event-loop/thread-pool pretty useless since everything has to wait for the sync cpu task to complete. There is no point adding more threads if the threads all serialized waiting a single thread sync waiting on cpu heavy (regex) task. 

We have tested this via fastapi/uvicorn api and this applies to all python event loops. Everything async/wait becomes serialized once heavy non-io blocking task is introduced such as cpu/gpu.

One way to unlock performance is to find the cpu hotspots and apply python.multiprocess to delegate the cpu tasks as not to block the eventloop feeding the gpu.  But gpuscall block too so the gpu model should run in another process so nothig blocks the event loop.
