### ISSUE TITLE
How can users configure the storage preferences for their KV-cache?

### ISSUE THREAD

**Issue by Guanlongwoo** [sgl-project/sglang#235]
Hi folks, new to SGLang,

How can users configure the storage preferences for their KV-cache, including whether to store it and the desired length of storage? Actually, in our scenario, storing the KV-cache for each user's response (from LLM) isn't necessary; we only need to store the KV-cache related to the question, and we would like these cache preserve as long as they can.

Best,

**Comment by hnyls2002** [comment]
@Guanlongwoo Our KV cache management automatically manages the cache across different requests. There are two key points of our design:
1. (LRU) Least Recent Used: We cache each request's KV cache by default unless there is not enough space. Then, we would evict the LRU requests to make more available space for newer ones.
2. (LPM) Longest Prefix Match: When multiple requests share a sequence of prefixes, we find the longest prefix and refresh the prefix's last used time. This promises the frequently shared prompt stay in our cache.

The actual management mechanism is a little more complex than the above. We have some benchmarks in this repo and you can have a look. Maybe our polices are what you need.

**Comment by William394873** [comment]
@hnyls2002 Thanks so much for the reply!

Yes I understand the two key points. But is there a way for users to not have their KV cache saved while still being able to use a shared KV cache? In fact, we've got lots of users hitting up the same big document. So, storing a cache for each user's answer doesn't really helpful since they only need the same shared cache of that big document. I'm aware that the LRU ensures the shared document's KV cache remains available. However, due to a high volume of requests, I'm trying to find a more efficient solution (that is, maybe only save the kv-cache of the first question of each user) that avoids the overhead of storing and then evicting individual user KV caches based on LRU, which could be costly.

Best,
