### ISSUE TITLE
[Feature Request] Optimized quantised kernels

### ISSUE THREAD

**Issue by nivibilla** [sgl-project/sglang#28]
https://github.com/IST-DASLab/marlin

**Comment by nivibilla** [comment]
https://github.com/AutoGPTQ/AutoGPTQ/pull/514

**Comment by qeternity** [comment]
Marlin kernels have been merged into vLLM: https://github.com/vllm-project/vllm/pull/2497

It would be good to get vLLM updated to 0.3.3 so that we can have these kernels. There have been some upstream changes around handling model configs, so for instance the Qwen imports are broken. I was going to open a PR but these might be bigger changes that @comaniac and others have views on how to handle.

I've uploaded a Marlin packed model to play around with: https://huggingface.co/qeternity/Nous-Hermes-2-SOLAR-10.7B-GPTQ-4bit-128g-actorder_False-Marlin

Performance (single `gen` invocation):

|        | 1   | 4   | 8   | 16   | 32   | 64   |
| ------ | --- | --- | --- | ---- | ---- | ---- |
| Marlin | 102 | 390 | 755 | 1422 | 2078 | 2476 |
| AWQ    | 79  | 303 | 582 | 1029 | 1416 | 1678 |


<img width="695" alt="image" src="https://github.com/sgl-project/sglang/assets/33002121/e062471e-43b5-4199-bd63-926ab85d28ca">

**Comment by nivibilla** [comment]
vllm is updated to 0.3.3 no?
