### ISSUE TITLE
SGLang Performance Compared with LMDeploy does not seem to have a significant improvement

### ISSUE THREAD

**Issue by cassiewilliam** [sgl-project/sglang#834]
# SGLang Performance Compared with LMDeploy

### Llama3.1-8B/Llama3-8B on 1 x A100 (bf16)

- vllm means: vllm-0.5.2
- sglang means: 0.2.6
- lmdeploy means: 0.5.2.post1

#### Offline Test(same with blog post  https://lmsys.org/blog/2024-07-25-sglang-llama3/)

Starting with the small model Llama-8B, the figure below shows the maximum output throughput each engine can achieve in offline settings across six different datasets. Both LMDeploy and SGLang can achieve an excellent throughput of up to 5000 tokens per second on a dataset with short inputs, while vLLM lags behind.

##### Output Throughput(High is Better)
![bar_plot_output_token_throughput](https://github.com/user-attachments/assets/4908939b-8bd4-42c9-aa45-9f5fe62a834f)
##### Mean Latency(Low is Better)
![bar_plot_mean_e2e_latency](https://github.com/user-attachments/assets/cd241a06-b115-4697-9068-ef1375b55837)
##### Median Latency(Low is Better)
![bar_plot_median_e2e_latency](https://github.com/user-attachments/assets/bce770af-e655-495f-9ee9-429260583f80)
##### Median TTFT(Low is Better)
![bar_plot_median_ttft](https://github.com/user-attachments/assets/db331b20-dce4-4cfb-9374-823d812bc7ff)
##### Median ITL(Low is Better)
![bar_plot_median_itl](https://github.com/user-attachments/assets/af61bf14-413b-42de-8ca7-7978cc3090ab)

#### Online Test(same with blog post  https://lmsys.org/blog/2024-07-25-sglang-llama3/)

The online benchmark figure below shows a trend similar to the offline case. TensorRT-LLM and SGLang perform equally well and can sustain an RPS > 10, while the latency of vLLM increases significantly at a high request rate.

##### Output Throughput(High is Better)
![linear_plot_output_token_throughput](https://github.com/user-attachments/assets/a03e87cf-37fa-4c9b-939b-8e7aabf2e1de)
##### Mean Latency(Low is Better)
![linear_plot_mean_e2e_latency](https://github.com/user-attachments/assets/05b2d049-0dfe-40e3-8dbc-8da1ebbee187)
##### Median Latency(Low is Better)
![linear_plot_median_e2e_latency](https://github.com/user-attachments/assets/0dbb9bdd-9cac-4445-bf05-78dbd124a0be)
##### Median TTFT(Low is Better)
![linear_plot_median_ttft](https://github.com/user-attachments/assets/efa8a7c1-ad81-46d1-902e-c49491ba6ab7)
##### Median ITL(Low is Better)
![linear_plot_median_itl](https://github.com/user-attachments/assets/190bd502-413b-4919-bc32-a7295b47aec3)

## Conclusion
- In the current test case, SGLang's performance is comparable to LMDeploy's, and it is indeed much faster than vLLM, and comparable to LMDeploy's performance. Aligning SGLang's scheduling can make vLLM's performance close to LMDeploy's (further analysis and optimization are underway)
- During vLLM's operation, GPU Utilization is too low, fluctuating from 0 to 60%. SGLang also has a GPU Utilization fluctuation of 20 to 80%, while the equivalent LMDeploy is basically close to 100%. From the perspective of GPU Utilization, SGLang should exceed LMDeploy to a certain extent. Do you have plans to continue to optimize and surpass LMDeploy in the future?

## Reference
[1] https://lmsys.org/blog/2024-07-25-sglang-llama3/

**Comment by zhyncs** [comment]
Hi @cassiewilliam Thank you for providing this information. In fact, I am a committer for both LMDeploy and SGLang, and I have also reserved a benchmark interface for LMDeploy in bench_serving. https://github.com/sgl-project/sglang/blob/1edd4e07d6ad52f4f63e7f6beaa5987c1e1cf621/python/sglang/bench_serving.py#L247 

Regarding the performance results of running Llama3 8B on a single A100 with LMDeploy, I was not surprised at all because I am very familiar with LMDeploy too. We did not include LMDeploy in the comparison in our blog post at that time because it currently does not support fp8, nor has it been specially optimized for H100 and TP. In subsequent blog releases, we will consider including it in the comparison, especially once it supports fp8. If you're interested, you can also benchmark in scenarios like A100 TP8, H100 TP8, and perhaps you'll make some discoveries.

Regarding the conclusion you mentioned, aligning vLLM with SGLang's scheduling might enhance vLLM's performance. The vLLM Team has been working overtime to reference the scheduling approach in SGLang since we published our blog, such as moving zmq-related implementations to vLLM, etc. As for how much the performance will improve after all is done, I am also very much looking forward to it. **We welcome competition very much.** I don't currently feel very optimistic about vLLM, the concise and efficient implementation of SGLang is still a huge advantage compared to vLLM.

GPU Util is sampled over time, showing 100% does not mean it is fully utilized, I think you should understand this basic situation. I have used both LMDeploy and TensorRT LLM, their GPU Util is very high, which is indeed well done. The low GPU Util of vLLM is due to its scheduling being implemented very inefficiently, with huge CPU scheduling overhead, which will be more evident on TP8 and H100.

SGLang has its own planning and roadmap, we will continue to advance at our own pace, maintaining a first-class level in terms of functionality and performance. SGLang will ensure both the ease of use and scalability of vLLM, as well as the performance of TensorRT LLM.

**Comment by zhyncs** [comment]
Additionally, I want to mention that the metrics we look at vary in different scenarios. For example, in **offline** scenarios, we pay more attention to **throughput** because the goal of offline is to increase throughput. In **online** scenarios, latency is very important, so we look at **end-to-end latency**. The metric for e2e latency here refers to the classic [Orca paper](https://www.usenix.org/conference/osdi22/presentation/yu) and means TTFT + (token_num - 1) * ITL. https://github.com/sgl-project/sglang/blob/1edd4e07d6ad52f4f63e7f6beaa5987c1e1cf621/python/sglang/bench_serving.py#L178 When either TTFT or ITL cannot hold up, e2e latency will dramatically increase. I hope this background information helps you understand these metrics better. Thanks.

**Comment by alan-hpc** [comment]
> Additionally, I want to mention that the metrics we look at vary in different scenarios. For example, in **offline** scenarios, we pay more attention to **throughput** because the goal of offline is to increase throughput. In **online** scenarios, latency is very important, so we look at **end-to-end latency**. The metric for e2e latency here refers to the classic [Orca paper](https://www.usenix.org/conference/osdi22/presentation/yu) and means TTFT + (token_num - 1) * ITL.
> 
> https://github.com/sgl-project/sglang/blob/1edd4e07d6ad52f4f63e7f6beaa5987c1e1cf621/python/sglang/bench_serving.py#L178
> 
> When either TTFT or ITL cannot hold up, e2e latency will dramatically increase. I hope this background information helps you understand these metrics better. Thanks.

Thank you for your replay，SGLang is a very nice job。

**Comment by zhyncs** [comment]
Thank you for your attention and support for SGLang. If you have plans to switch to the inference stack in the future, as now LLM inference frameworks all support OpenAI-compatible servers, switching has become very easy and smooth. Feel free to contact us at any time, we are more than willing to provide technical support and help. By the way, my mentee who was previously at Meituan recently moved to Shopee, maybe you are colleagues LOL. This issue is closed for now, feel free to reopen it if needed in the future. Thank you.

**Comment by jon-chuang** [comment]
Hello @zhyncs may I know what you attribute the perf of sglang over vllm to? Is it primarily due to better kernels for decode like from flash infer?

**Comment by zhyncs** [comment]
Efficient scheduling and a substantial amount of engineering optimization.

**Comment by sitabulaixizawaluduo** [comment]
> Additionally, I want to mention that the metrics we look at vary in different scenarios. For example, in **offline** scenarios, we pay more attention to **throughput** because the goal of offline is to increase throughput. In **online** scenarios, latency is very important, so we look at **end-to-end latency**. The metric for e2e latency here refers to the classic [Orca paper](https://www.usenix.org/conference/osdi22/presentation/yu) and means TTFT + (token_num - 1) * ITL.
> 
> https://github.com/sgl-project/sglang/blob/1edd4e07d6ad52f4f63e7f6beaa5987c1e1cf621/python/sglang/bench_serving.py#L178
> 
> When either TTFT or ITL cannot hold up, e2e latency will dramatically increase. I hope this background information helps you understand these metrics better. Thanks.

Shouldn't E2E latency mean TTFT + (token_num - 1) * TPOT?
